title: Takayuki OGI（荻 多加之）
description: >-
  PhD in Neuroscience (神経科学).
  Research interests: inferior temporal cortex (下側頭葉皮質), metascience (メタサイエンス), natural language processing (自然言語処理).
  Research Administrator (URA) at Fukushima University.
  Research Associate Professor at JAIST.
  Visiting Researcher at Fukushima Medical University.
url: "https://takayuki1997.github.io"
baseurl: ""

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
