title: Takayuki OGI（荻 多加之）
description: >-
  PhD in Neuroscience.
  Research Administrator at Fukushima University.
  Research Associate Professor at JAIST.
  Visiting Researcher at Fukushima Medical University.
url: "https://takayuki1997.github.io"
baseurl: ""

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
